### ISSUE TITLE
Description for types of waste in Legend 

### ISSUE THREAD

**Issue by ychoy** [descartae/android#41]
Currently, user can see Lorem ipsum text under each type of waste. 

Proposal: provide a description for the type of waste.

**Comment by lucasmontano** [comment]
Hi @ychoy ! Actually, the Android App is fetching the Type of Waste description properly as you can see [here](https://github.com/descartae/android/blob/a74bd23d4ca2eba6c1b0af5a7b996e97a08fba1b/app/src/main/graphql/org/descartae/android/TypeOfWasteQuery.graphql) and [here](https://github.com/descartae/android/blob/5c23bdf3eeeb3a9f249b5e562c835bd785f986a0/app/src/main/java/org/descartae/android/adapters/LegendWasteTypeListAdapter.kt) :)

So, I think this issue shouldn't be opened as an "Android Issue", as we can't fix this information on the client side.
